### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by RaymondMouthaan**
Full dutch translation
Typo corrected in EN file

### CODE REVIEW

**Comment by reloxx13** [comment]
thank you very much 👍 

Veel dank :p

**Comment by RaymondMouthaan** [comment]
Your welcome 💯

**Comment by reloxx13** [comment]
there is a new block missing from yesterday update:

```
[DEVICES_AUTOSCAN]
BTN_START_AUTOSCAN = "Start AutoScan"
FROM_IP = "From IP"
FROM_IP_HELP = "IP to begin the AutoScan"
TO_IP = "To IP"
TO_IP_HELP = "IP to end the AutoScan"
MSG_DEVICES_FOUND_COUNT = "Devices found"
MSG_DEVICES_ADD_DONE = "Devices added!"
MSG_NO_DEVICES_FOUND = "No devices found!"
MSG_SCANNING = "AutoScan scanning..."
DEVICE = "Device"
BTN_SAVE_ALL = "Save All"
BTN_TEST = "Test"
```

**Comment by RaymondMouthaan** [comment]
Crap something went wrong while merging i guess, ill fix it okay?

**Comment by reloxx13** [comment]
nuu no problem, i just merged it correctly, just need the translations for the new keys

**Pull request merged**
